### ISSUE TITLE
App crashes when scrolling long list

### ISSUE THREAD

**Issue by khalid-hussain** [khalid-hussain/HisnulMuslim#35]
For some reason, the app crashes when scrolling a long list. 

**Tested on**
1. Nexus 7 2013 running 5.1.1.
2. Samsung Galaxy Note 2 N7100  running Cyanogenmod unofficial 5.1.1.

**Possible definition of error from logcat**

```
06-05 00:48:26.116  16045-16045/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.khalid.hisnulmuslim, PID: 16045
    java.lang.IndexOutOfBoundsException
            at android.view.GLES20Canvas.drawText(GLES20Canvas.java:888)
            at com.bluejamesbond.text.Styled.drawUniformRun(Styled.java:156)
            at com.bluejamesbond.text.Styled.drawDirectionalRun(Styled.java:319)
            at com.bluejamesbond.text.Styled.drawText(Styled.java:383)
            at com.bluejamesbond.text.SpannableDocumentLayout.onDraw(SpannableDocumentLayout.java:512)
            at com.bluejamesbond.text.IDocumentLayout.draw(IDocumentLayout.java:143)
            at com.bluejamesbond.text.DocumentView.drawLayout(DocumentView.java:184)
            at com.bluejamesbond.text.DocumentView.onDraw(DocumentView.java:620)
            at android.view.View.draw(View.java:15239)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at android.widget.ScrollView.draw(ScrollView.java:1689)
            at android.view.View.updateDisplayListIfDirty(View.java:14175)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.view.View.updateDisplayListIfDirty(View.java:14170)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.view.View.draw(View.java:15242)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at android.view.View.updateDisplayListIfDirty(View.java:14175)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.view.View.updateDisplayListIfDirty(View.java:14170)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.View.draw(View.java:14967)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
            at android.widget.ListView.drawChild(ListView.java:3396)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
            at android.widget.AbsListView.dispatchDraw(AbsListView.java:2605)
            at android.widget.ListView.dispatchDraw(ListView.java:3391)
            at android.view.View.draw(View.java:15242)
            at android.widget.AbsListView.draw(AbsListView.java:4116)
            at android.view.View.updateDisplayListIfDirty(View.java:14175)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
            at android.view.View.updateDisplayListIfDirty(View.java:14135)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
            at android.view.View.updateDisplayListIfDirty(View.java:14135)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
            at android.view.View.updateDisplayListIfDirty(View.java:14135)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
            at android.view.View.updateDisplayListIfDirty(View.java:14135)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
            at android.view.View.updateDisplayListIfDirty(View.java:14135)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
            at android.view.View.updateDisplayListIfDirty(View.java:14135)
            at android.view.View.getDisplayList(View.java:14197)
            at android.view.Threade
```

**Some ideas**
1. Could be due to Android L 5.1.1.
2. Might be related to TextJustify library.

**Steps to reproduce**
1. Scroll to a section with a number of dua to necessitate scrolling, e.g. Category 16: Supplications at the start of Salah.
2. Scroll down and it should crash. If it doesn't, try scrolling back up and repeat until you are met with the crash.

**Comment by ahmedre** [comment]
looks like a bug in TextJustify library. i'll file it.
